# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
header-img: img/touxiang.png
email: wangrenjun12@sina.com
description: > # this means to ignore newlines until "baseurl:"
   青青子净 悠悠我心  但为君故 沉吟至今   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jianshu.com/u/3893b994f388" # the base hostname & protocol for your site
twitter_username: wangrenjun12
github_username:  wangrenjun12

# Build settings
markdown: kramdown
